name: ci-lint
channels:
- conda-forge
dependencies:
- python
- black
- isort
- pylint
- mypy
- clang-format
- tqdm
- pytorch-cpu
- attrs
- cloudpickle
- decorator
- ml_dtypes
- numpy
- scipy
- tornado
- pytest
