name: tlcpack-build

channels:
  - conda-forge
  - anaconda

dependencies:
  - llvmdev>=15
  - cmake>=3.24
  - zlib
  - zstd-static
  - git
  - conda-build
  - anaconda-client
  - numpy
  - pytest
  - bzip2
  - scipy
  - pip
  - cython
  - libvulkan-headers
  - libvulkan-loader
  - spirv-tools
  - spirv-headers
  - rust
  - rhash  # [osx]
